version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 82:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - TESTSUITE_PASSWORD=
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sistemaDeCadatro
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
